# Generated by Django 5.2.6 on 2025-09-07 17:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_edital', models.CharField(max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('unidade_demandante_nome', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Aguardando Homologação', 'Aguardando Homologação'), ('Homologado', 'Homologado'), ('Recusado', 'Recusado'), ('Ativo', 'Ativo'), ('Finalizado', 'Finalizado')], default='Rascunho', max_length=30)),
                ('valor_empenho', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editais_criados', to=settings.AUTH_USER_MODEL)),
                ('homologado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='editais_homologados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Edital',
                'verbose_name_plural': 'Editais',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('servidores_alocados', models.ManyToManyField(blank=True, related_name='atividades_alocadas', to=settings.AUTH_USER_MODEL)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.edital')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horas', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('descricao_justificativa', models.TextField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Recusado', 'Recusado')], default='Pendente', max_length=20)),
                ('comentario_recusa', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='core.atividade')),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='core.edital')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lançamento de Hora',
                'verbose_name_plural': 'Lançamentos de Horas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ServidorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siape', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('setor', models.CharField(blank=True, max_length=100)),
                ('funcao', models.CharField(choices=[('Unidade Demandante', 'Unidade Demandante'), ('PRODGEP/PROPEG', 'PRODGEP/PROPEG'), ('Servidor', 'Servidor')], default='Servidor', max_length=30)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('limite_horas_anual', models.IntegerField(default=120)),
                ('horas_utilizadas', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
