# Generated by Django 5.2.6 on 2025-09-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentohoras',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Recusado', 'Recusado'), ('Homologado', 'Homologado'), ('Revertido', 'Revertido pela PRODGEP')], default='Pendente', max_length=20),
        ),
    ]
