# Generated by Django 5.2.6 on 2025-09-15 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_lancamentohoras_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sigla", models.CharField(max_length=20, unique=True)),
                ("nome", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Unidade Organizacional",
                "verbose_name_plural": "Unidades Organizacionais",
                "ordering": ["sigla"],
            },
        ),
        migrations.AddField(
            model_name="atividade",
            name="descricao",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servidorprofile",
            name="titulacao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Graduação", "Graduação"),
                    ("Especialização", "Especialização"),
                    ("Mestrado", "Mestrado"),
                    ("Doutorado", "Doutorado"),
                    ("Pós-Doutorado", "Pós-Doutorado"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tipoatividade",
            name="vinculo",
            field=models.CharField(
                choices=[
                    ("Concurso", "Concurso Público"),
                    ("Processo", "Processo Seletivo"),
                    ("Ambos", "Ambos"),
                ],
                default="Ambos",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="servidorprofile",
            name="unidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="servidores",
                to="core.unidade",
            ),
        ),
    ]
