# Generated by Django 5.2.6 on 2025-09-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_unidade_atividade_descricao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="edital",
            name="justificativa_recusa",
            field=models.TextField(blank=True, null=True),
        ),
    ]
