# Generated by Django 5.2.6 on 2025-10-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidorprofile',
            name='funcao',
            field=models.CharField(choices=[('Servidor', 'Servidor'), ('Unidade Demandante', 'Unidade Demandante'), ('PRODGEP/PROPEG', 'PRODGEP/PROPEG')], default='Servidor', max_length=30),
        ),
    ]
